server:
  port: 8080
spring:
  application:
    name: customer-service
  datasource:
    driverClassName: org.postgresql.Driver
    username: 'postgres'
    url: jdbc:postgresql://postgres:5432/customer
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
