server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'postgres'
  jpa:
    hibernate:
     ddl-auto: create-drop
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false