server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'postgres'
  jpa:
    hibernate:
     ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka