server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka